### ISSUE TITLE
Mark the package as a favorite

### ISSUE THREAD

**Issue by lakipatel** [tightenco/novapackages-issues#1]
I have one suggestion, can we mark the package as a favorite?

**Comment by mattstauffer** [comment]
Could you tell a little more about what the goal is? Would this be for you to save a list for easier user later? Or something else?

**Comment by lakipatel** [comment]
Sure, My goal is, I want my favorite packages in the separate section.
I am sure after some week or months we will have a huge amount of packages so the users can easily find their packages which they marked as favorite.

For example, you can check https://packagist.org/.
here you will find the separate section for **My favorites** so any time if I need my favorite package I can get it from there.

**Comment by vmitchell85** [comment]
I would also like this feature.

**Comment by MDooley47** [comment]
I would like this as well. Either a favorite or some other saved for later method.

**Comment by niladam** [comment]
Apparently this has been implemented (though it needs some more work) and can probably be closed.

**Comment by ctroms** [comment]
This has been implemented recently. To mark a package as favorited, click on a package's title to view the details, then click the `Add to Favorites` link in the right hand column. Once favorited, you can remove the package from your favorites in the same place. To view all of your favorites, click the `packages` link in the main navigation at the top of the site. @niladam would you please provide an example of something missing from this feature that you would like to see?

**Comment by niladam** [comment]
@ctroms -- well, i think the wording is not pretty clear.

Upon inspecting a package, you're presented with the text "0 Favorites" as in the screenshot. This could incorrectly lead to people thinking 'no-one addded this to their favourites';

<p align="center"><img width="318" alt="screenshot 2018-11-10 22 20 32" src="https://user-images.githubusercontent.com/4151765/48305632-07b40380-e537-11e8-9657-4f9a2adbc8a2.png"></p>

One idea is that this could just show me an **ADD TO FAVORITES** button if i don't have this already added, or just show me an **REMOVE FROM FAVORITES** if i do. It's more concise and easier to grasp.

If there are any stats based on the number of times a package has been favorited, that could be presented in a similar fashion like: 33 people already favorited this ?

Also, the positioning of the favorites section is IMHO not really well thought out. I -- personally -- think that Packages -- is probably a link to either the index of the packages or to the homepage.

Maybe something like in the screenshot below ?

<p align="center"><img width="353" alt="screenshot 2018-11-10 22 37 33" src="https://user-images.githubusercontent.com/4151765/48305763-49de4480-e539-11e8-8019-64896bc7d330.png"></p>

Just my 2 cents :)

**Comment by ctroms** [comment]
@niladam Thanks for the comments and screenshots. 

"0 Favorites" is meant to imply that no one has favorited the package. If multiple users have favorited the package, that text will reflect the total number of favorites from all users. Also, the "Add to Favorites" text link should display "Add to Favorites" if you have not already favorited the package, and "Remove Favorite" if you have already favorited it.  Are you experiencing something different?

I see what you mean regarding the placement of the users favorites section. I'll be sure to bring this up with the rest of the team as well as the UI change from text link to button you mentioned. 

I'm closing this issue because the original issue of not having favorites at all is resolved but know that we will likely make additional changes to improve the UI and your suggestions will be considered. 

Thanks again for your input!
