### ISSUE TITLE
Add an RSS feed for new packages

### ISSUE THREAD

**Issue by AaronHolbrook** [tightenco/novapackages-issues#10]
Something to be able to monitor new arrivals would be awesome

**Comment by mattstauffer** [comment]
@vootrunner You'll enjoy the new home page's "Recent" section, I think. Right now it just shows the latest 6 entries, but we'll probably keep refining how to get the best "recent additions" list out of there.

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/151829/44806149-2a6b8880-ab94-11e8-8375-538933e1ffb1.png">

@AaronHolbrook Sounds like a good idea. We have an API but I can see how there's a lot of tooling that makes RSS valuable, too.

**Comment by vootrunner** [comment]
@mattstauffer - probably not as useful as something time based. If the last 6 packages encompass a span of something less than the period of time since my last visit,  then there isn't a way to discover new submissions in that interval. Finding new stuff only gets more difficult as the number of packages increases.

With a time bound filter, I can be assured that if I visit within the time boundary, I won't miss anything. I can browse through the list (hopefully sorted from newest to oldest) until I see things I remember seeing before.

You could also timestamp the creation date for each entry, track last login time and filter the list based on that and display it as 'New to You.'  I mean, I can dream, right?

Thanks for putting this all together. It's a great resource!

**Comment by mattstauffer** [comment]
https://novapackages.com/feeds/recent

**Comment by mattstauffer** [comment]
@vootrunner yah, I'm aware there are more things we can do. Please feel free to open a new issue for discussion of how to iterate on that "recent" section if you'd like--thanks! So glad you're liking it :)
