### ISSUE TITLE
Add a comment field for Package ratings

### ISSUE THREAD

**Issue by lesaff** [tightenco/novapackages-issues#29]
FR: Add comment field for ratings. 

I think it would be nice to be able to see why people rate certain packages as 5 stars or 1 star. As a potential package user, I would like to know why it was rated highly or poorly. I am sure package authors would love to see real feedback rather than just stars.

What do you think?

**Comment by mattstauffer** [comment]
Totally agreed! We've discussed it in a few other issues and I completely agree it's a good idea.

**Comment by vootrunner** [comment]
It would be nice to see something displayed on a package's card that would help a consumer form an opinion of the "health" and "quality" of a package. This becomes more of an issue over time as packages are abandoned, superseded by features added to Nova directly, become broken by Nova updates etc.

Being a "Popular package" (not sure how that is measured. Clickthroughs?) lends an air of legitimacy to a package, but how many are reviewed and quickly discarded? There is at least one package in the 'Popular' list that has a key feature that has been broken for about a month and the author stopped responding to issues about 3 weeks ago. I know, open source, free time, I get that, but in the current, fast-moving world of Nova, that is a significant duration of non-activity, particularly for a broken package.

I can provide more specific examples privately so as not to embarrass any package authors if that will help.

Perhaps just something as simple as the package author is required to indicate which version of Nova the package works with and is required to manually update that to indicate compliance with newer versions of Nova, coupled with an alert on the package detail page that indicates if the package works with the current Nova release.

I appreciate all of the work that has gone into novapackages.com, and as the site matures, I think some indication of package quality and ongoing health is an important value-add. 

I'd consider a small subscription fee for a curated list of packages that met some minimal validation rules with alerts when a package failed validation against new releases.

Guess who's wasted lots of time testing and discarding packages in the last couple of days?

**Comment by mattstauffer** [comment]
@vootrunner I think this is a lot of really good thinking here.

Right now popularity is a combination of GitHub stars and Packagist downloads. We also plan to add the ratings to that calculation.

I've been thinking of the way WordPress shows "compatible with" but haven't yet dug into how they actually figure that out.

I wonder; before we build a system like that, would it be helpful to have some sort of way for folks to flag a package as broken? Or no, since it's really just broken for a specific version?

Thank you so much for this input--please keep it coming!

**Comment by vootrunner** [comment]
The more I think about flagging packages as broken, the more it just feels a little too easy to game and to do it right it starts to get heavy.

Pure spit-balling, but how about calculating  a star score over the last X days and compare that to the average score on the last X months and show either an up or down arrow indicating the quality trend over time. (e.g. 4.5 and falling or 3.8 and rising). Not sure if that is clear, let me know if it isn't.

If you decide flagging as broken is a good idea, then I'd at least offer these suggestions:

- The flagger should be required to add text to specify what is broken
- The package owner should be able to  unflag their project, along with a required comment 
- A threshold of broken votes from unique logged in users (2? 3?) would be a safeguard against single user pilot error or malicious intent. 
- The package owner should receive a notice that their package has been flagged as broken along with the process/requirements to unflag it after the issue has been corrected.
- Set a threshold of 'broken' flags for a package that, if exceeded, cause it to no longer be listed or searchable until the owner marked it as no longer broken.

I'd also argue that packages marked as broken due to poor documentation that cross a threshold should still require a fix (updated docs) before being unflagged.

**Comment by mattstauffer** [comment]
Added :) Please consider moving any conversation about "broken" to #63.
